### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by legodude17** [Coalpha/core.js#9]
Things we need to do for tests:
 * [x] Have tests that run (done, #7)
 * [ ] Test modules.js (pending, #8)
 * [ ] Test event-stream.js (pending, #8)
 * [ ] Test css-core.js (@Coalpha should do it)
